ARG GOSDL2_VERSION=latest

FROM ymohlcl/gosdl2:$GOSDL2_VERSION

ARG ARTIFACT_NAME=bin
ARG PATH_TO_WORKDIR=/github/workspace

ENV PATH_TO_WORKDIR=$PATH_TO_WORKDIR
ENV ARTIFACT_NAME=$ARTIFACT_NAME

WORKDIR /go/src/app
COPY . .

# run default rules
RUN make ci-build

ENTRYPOINT mv "/go/src/app/${ARTIFACT_NAME}" "${PATH_TO_WORKDIR}"
